### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by stonebig** [nasa/PyAMPR#2]
any plan for a Python3 compatibility ?

**Comment by tjlang** [comment]
Long term? Probably yes. But it kind of depends where the community goes. Python3 doesn't seem to have much traction currently in the US radar/radiometer community. People are still working on going from other languages to Python.

**Comment by astrofrog** [comment]
Just to add that there is a bit of chicken and egg problem - as long as most packages don't support Python 3, users will stay with Python 2. So as developers, we shouldn't wait for most users use Python 3 before making packages compatible.

Given that this is a pure-Python package, supporting Python 3 should be pretty easy. The only real issue is that there doesn't appear to be a test suite, so making absolutely sure that Python 3 works will not be easy - but running the notebook might give a first impression.

**Comment by astrofrog** [comment]
Just for info, I've actually made all the fixes (I think) required for Python 3 locally in the last 10 minutes, but I can't test this since I need some example data files. I opened an issue in #3 to say that I think it would be good to ship this with a test suite include one or two example data files so that anyone making changes to this can run the tests. I can provide advice if needed.

**Comment by tjlang** [comment]
PyAMPR now updated, tested, and working under Python 2.7 as well as 3.4.

**Comment by stonebig** [comment]
great ! thanks
