### ISSUE TITLE
Add test suite

### ISSUE THREAD

**Issue by astrofrog** [nasa/PyAMPR#3]
It would be good to have a test suite, even small, with an example file, which can be run to make sure that things are working correctly. This will be needed to ensure that any Python 3 transition does not break Python 2 compatibility (see #2). Once the test suite is written, a Continuous integration service like Travis can be used. Ping me if you would like advice on setting up Travis!

**Comment by tjlang** [comment]
I'm open to this, but I probably would need some help. A lot of the testing I have done is relatively informal, and via IPython notebooks. Does the updated program read in the data like it's supposed to? Do the plotting methods show the data like they are supposed to look? If I print out data slices, are they what they should be? That sort of thing. I don't currently have a formal testing suite, a set of unit tests, or anything like that. 

I just updated the package by adding two sample data files. AMPR's data home is at ghrc.nsstc.nasa.gov if we need more. The netCDF IPHEx data are still embargoed, so I can't share those just yet. This means the netCDF read methods are not publicly testable.

**Comment by astrofrog** [comment]
@tjlang - all the things you mentioned can be tested via a formal testing suite, though plotting is a little tricky (but one can at least it runs without crashing).

I recommend using pytest for testing. Basically a test is just a function that raises an error if the test fails. So for example, a test that fails is:

```
def test_fails():
    assert 1 == 2
```

You can put all tests in files with a name starting with `test_` and the functions names should start with `test`. Then if you do this you can run the tests with the command `py.test`. I can add a test to demonstrate how to do this and also how to access data files.

**Comment by tjlang** [comment]
OK, thanks. I think what might be really helpful is if you can devise a fairly simple but AMPR-specific test, and post that sample code. Then I might be able to get a better sense of how to approach a testing suite. Seems like every unit test tutorial I see on the Internet wants to test "foo" vs. "bar," and thus is too abstract and general to be very useful. It's why I've shied away from doing this before now.

**Comment by tjlang** [comment]
I looked into writing unit tests. I am just not sure they are that useful to PyAMPR, since a healthy chunk of the code relates to plotting data. Moreover, Just about every unit test tutorial I've seen is not relevant to scientific applications. The testing modules are not particularly intuitive or easy to use either. 

What does make sense to me is an additional testing notebook with sample images to compare against, to make sure key PyAMPR elements do not get broken by future upgrades. So that is what I have provided in the latest commit. This notebook is complementary to the demonstration notebook. Taken together, they provide a way to test various components of the package using real data. It's not as formalized as focused unit tests, but I think it is way more intuitive approach for a science user of the package.
